# Generated by Django 5.1.2 on 2024-10-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Discharged', 'Discharged'), ('Suspended', 'Suspended')], max_length=50, null=True),
        ),
    ]
