# Generated by Django 5.1.2 on 2024-12-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('panelAdmin', '0003_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panelAdmin.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panelAdmin.client'),
        ),
        migrations.AddField(
            model_name='room',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panelAdmin.client'),
        ),
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panelAdmin.client'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panelAdmin.client'),
        ),
    ]
