# Generated by Django 5.1.2 on 2025-10-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_equipment_room_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='session',
            name='canceled_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rescheduled_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='pacientes.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='objective',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Pendiente sin planificar', 'Pendiente sin planificar'), ('Pendiente planificada', 'Pendiente planificada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente sin planificar', help_text='Flujo: Pendiente sin planificar → Pendiente planificada → Realizada | Cancelada.', max_length=30),
        ),
    ]
