# Generated by Django 5.1.2 on 2024-11-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='new_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reserved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reserved_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
