# Generated by Django 5.1.2 on 2024-11-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_patient_cost_session_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='session',
            name='new_activity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='reserved_time',
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text="Estado de la sesión: 'Pending', 'Completed' o 'Cancelled'.", max_length=10),
        ),
    ]
