# Generated by Django 5.1.2 on 2025-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='pacientes.equipment'),
        ),
    ]
