# Generated by Django 5.1.2 on 2025-10-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_room_equipment'),
        ('panelAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='comp_type',
            field=models.CharField(choices=[('fixed', 'Fijo mensual'), ('percent', '% por sesión')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='specialist',
            name='comp_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='panelAdmin.client')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
