# Generated by Django 5.1.2 on 2024-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pending', help_text="Estado de la sesión: 'Pending', 'Completed' o 'Cancelled'.", max_length=10),
        ),
    ]
