# Generated by Django 5.1.2 on 2025-10-16 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_specialist_comp_type_specialist_comp_value_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='client',
        ),
    ]
