# Generated by Django 5.1.2 on 2024-11-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid_in_advance',
            field=models.BooleanField(default=False, verbose_name='Pagada por adelantado'),
        ),
    ]
