# Generated by Django 5.1.2 on 2025-10-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_payment_method_payment_reference'),
    ]

    operations = [
        # Migración vacía - el campo client ya existe desde 0006
        # Las migraciones 0007 y 0009 se neutralizan mutuamente
    ]