# Generated by Django 5.1.2 on 2024-12-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('database_name', models.CharField(max_length=255, unique=True)),
                ('specialists_limit', models.PositiveIntegerField(default=4)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('morose', 'Moroso'), ('suspended', 'Suspendido')], default='active', max_length=10)),
            ],
        ),
    ]
