# Generated by Django 5.1.2 on 2024-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(default='default_user', max_length=255),
        ),
    ]
