# Generated by Django 5.1.2 on 2024-12-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelAdmin', '0004_remove_client_admin_email_client_initial_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
